databases:
  - name: server
    databaseName: server
    user: server
    region: singapore

services:
  - type: web
    name: server
    env: python
    region: singapore
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn server.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: server
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4